### PR TITLE
Log Mel Spectrogram implemented

### PR DESCRIPTION
**Pull request by MJelinek**

### CODE REVIEW

**Review by zackjeanroy — COMMENTED** [review]
I think it's fine :)

**Comment by Alyssb** [comment]
It could be divided into classes and functions a little more, but we can do that later.

**Comment by Alyssb** [comment]
*** other than that it looks great to me

**Review by mr-stephen-carr — APPROVED** [review]
I was able to run it on my machine without issue, and it produced everything just fine! Looks good.

**Pull request merged**
